### ISSUE TITLE
Fail to load dependency graph

### ISSUE THREAD

**Issue by sjmjulia** [ATF19/react-native-shop-ui#1]
The error info is as follows:
ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1282:11)

And on ios simulator, it seems that i need to set server?
![image](https://user-images.githubusercontent.com/5000788/33005890-075a7302-ce03-11e7-8692-9f56e2d6e0ea.png)

**Comment by ATF19** [comment]
@sjmjulia did you start the server ? If not run the following command to start it `react-native start` and then reload with command+r
